import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { createDiagram, listComponentTypes, renderDiagram, updateDiagram, type DiagramInput } from "./tools";

const pinRefShape = {
  component: z.string().min(1).describe("id of a component in this diagram"),
  pin: z.string().min(1).describe("pin name defined by that component's type"),
};

const componentShape = {
  id: z.string().min(1).describe("Unique id for this component instance within the diagram, e.g. 'esp32-1'"),
  type: z.string().min(1).describe("Component type key, e.g. 'esp32'. See list_component_types for valid values."),
  label: z.string().optional().describe("Optional display label override"),
};

const connectionShape = {
  id: z.string().optional(),
  from: z.object(pinRefShape),
  to: z.object(pinRefShape),
};

const diagramInputShape = {
  diagramId: z.uuid().describe("UUID for this diagram, generated by the caller."),
  title: z.string().optional().describe("Optional human-readable name for the diagram."),
  components: z.array(z.object(componentShape)).describe("Every component instance placed on the diagram."),
  connections: z.array(z.object(connectionShape)).describe("Pin-to-pin wires between components."),
};

function errorResult(errors: string[]) {
  return {
    isError: true,
    content: [{ type: "text" as const, text: `Diagram is invalid:\n${errors.map((e) => `- ${e}`).join("\n")}` }],
  };
}

function diagramSummary(action: string, diagram: DiagramInput) {
  return {
    content: [
      {
        type: "text" as const,
        text: `${action} diagram "${diagram.diagramId}" with ${diagram.components.length} component(s) and ${diagram.connections.length} connection(s). Call render_diagram to generate an image.`,
      },
    ],
    structuredContent: {
      diagramId: diagram.diagramId,
      componentCount: diagram.components.length,
      connectionCount: diagram.connections.length,
    },
  };
}

export function createDiagramMcpServer(): McpServer {
  const server = new McpServer({ name: "electronics-diagrams", version: "1.0.0" });

  server.registerTool(
    "create_diagram",
    {
      title: "Create diagram",
      description:
        "Creates a new electronics diagram from components and pin-to-pin connections. The caller generates a fresh UUID and passes it as diagramId; fails if that id is already in use. Component placement and wire routing are computed automatically. Call list_component_types first to see valid component types and pins.",
      inputSchema: diagramInputShape,
    },
    async (input) => {
      const result = await createDiagram(input);
      return result.ok ? diagramSummary("Created", input) : errorResult(result.errors);
    },
  );

  server.registerTool(
    "update_diagram",
    {
      title: "Update diagram",
      description:
        "Replaces the components and connections of an existing diagram (identified by diagramId). Fails if the diagram doesn't exist yet — use create_diagram first. Send the full desired state, not just the changed parts.",
      inputSchema: diagramInputShape,
    },
    async (input) => {
      const result = await updateDiagram(input);
      return result.ok ? diagramSummary("Updated", input) : errorResult(result.errors);
    },
  );

  server.registerTool(
    "render_diagram",
    {
      title: "Render diagram",
      description:
        "Renders a diagram to a JPEG image and returns it inline plus a public URL (/view/{diagramId}) you can show or link to.",
      inputSchema: { diagramId: z.uuid() },
    },
    async ({ diagramId }) => {
      const result = await renderDiagram(diagramId);
      if (!result.ok) return errorResult(result.errors);

      return {
        content: [
          { type: "text" as const, text: `Rendered diagram. View it at ${result.viewUrl}` },
          { type: "image" as const, data: result.jpeg.toString("base64"), mimeType: "image/jpeg" },
        ],
        structuredContent: {
          diagramId: result.diagramId,
          viewUrl: result.viewUrl,
          imageUrl: result.imageUrl,
        },
      };
    },
  );

  server.registerTool(
    "list_component_types",
    {
      title: "List component types",
      description:
        "Lists every component type available for use in diagrams, including its pins. Call this before building a diagram to know what's available and how to wire it.",
    },
    async () => {
      const types = listComponentTypes();
      return {
        content: [{ type: "text" as const, text: JSON.stringify(types, null, 2) }],
        structuredContent: { componentTypes: types },
      };
    },
  );

  return server;
}
