import { z } from "zod";

const pinRefShape = {
  component: z.string().min(1).describe("id of a component in this diagram"),
  pin: z.string().min(1).describe("pin name defined by that component's type"),
};

const componentShape = {
  id: z.string().min(1).describe("Unique id for this component instance within the diagram, e.g. 'esp32-1'"),
  type: z.string().min(1).describe("Component type key, e.g. 'esp32'. See list_component_types for valid values."),
  label: z.string().optional().describe("Optional display label override"),
};

const connectionShape = {
  id: z.string().optional().describe("Optional identifier for this connection"),
  from: z.object(pinRefShape).describe("Source pin"),
  to: z.object(pinRefShape).describe("Destination pin"),
};

export const diagramInputShape = {
  diagramId: z.uuid().describe("UUID for this diagram, generated by the caller."),
  title: z.string().optional().describe("Optional human-readable name for the diagram."),
  components: z.array(z.object(componentShape)).describe("Every component instance placed on the diagram."),
  connections: z.array(z.object(connectionShape)).describe("Pin-to-pin wires between components."),
};

export const renderDiagramInputShape = {
  diagramId: z.uuid().describe("UUID of an existing diagram"),
};

/** Loose shape used only where exact per-field zod types don't matter (e.g. rendering docs). */
export interface ToolDefinition {
  name: string;
  title: string;
  description: string;
  inputShape?: Record<string, z.ZodType>;
}

export const listComponentTypesTool = {
  name: "list_component_types",
  title: "List component types",
  description:
    "Lists every component type available for use in diagrams, including its pins. Call this before building a diagram to know what's available and how to wire it.",
} satisfies ToolDefinition;

export const createDiagramTool = {
  name: "create_diagram",
  title: "Create diagram",
  description:
    "Creates a new electronics diagram from components and pin-to-pin connections. The caller generates a fresh UUID and passes it as diagramId; fails if that id is already in use. Component placement and wire routing are computed automatically. Call list_component_types first to see valid component types and pins.",
  inputShape: diagramInputShape,
} satisfies ToolDefinition;

export const updateDiagramTool = {
  name: "update_diagram",
  title: "Update diagram",
  description:
    "Replaces the components and connections of an existing diagram (identified by diagramId). Fails if the diagram doesn't exist yet — use create_diagram first. Send the full desired state, not just the changed parts.",
  inputShape: diagramInputShape,
} satisfies ToolDefinition;

export const renderDiagramTool = {
  name: "render_diagram",
  title: "Render diagram",
  description:
    "Renders a diagram to a JPEG image and returns it inline plus a public URL (/view/{diagramId}) you can show or link to.",
  inputShape: renderDiagramInputShape,
} satisfies ToolDefinition;

/** For iterating over every tool generically (e.g. to render docs). Individual exports above keep their precise types for registerTool's inference. */
export const toolDefinitions: ToolDefinition[] = [
  listComponentTypesTool,
  createDiagramTool,
  updateDiagramTool,
  renderDiagramTool,
];
